### ISSUE TITLE
Language choice?

### ISSUE THREAD

**Issue by EdmanJohan** [willeagren/advent-of-code#1]
Is Python even a real programming language? Like, really?

[<img src="https://external-preview.redd.it/3WXfG7x4CdwBe8qXqxcIW9cKBUkWx8UI9j1kPmZW6nE.jpg?auto=webp&s=dd91fe7ed3fae15140b11e8335926308274a5c39">](http://google.com.au/)

**Comment by wilhelmagren** [comment]
It very much is. But for the sake of complexity, I will continue this AoC in Rust!
![bild](https://raw.githubusercontent.com/rochacbruno/rust_memes/master/img/python_for_kids.jpg)
